# Generated by Django 4.1.3 on 2022-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('client', 'client'), ('assistant', 'assistant'), ('administrator', 'administrator')], default='client', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
