# Generated by Django 4.1.4 on 2022-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'administrator'), ('AS', 'assistant'), ('CL', 'client')], default='CL', max_length=2),
        ),
    ]
