# Generated by Django 4.1.4 on 2022-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=200)),
                ("url_media", models.URLField(max_length=300)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
    ]
