# Generated by Django 4.1.4 on 2023-01-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_image',
            field=models.URLField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_origin',
            field=models.URLField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_address',
            field=models.CharField(max_length=500),
        ),
    ]
