# Generated by Django 4.1.4 on 2022-12-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos_base', '0002_alter_baseproduct_visit_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('url_image', models.URLField(max_length=500)),
                ('url_origin', models.URLField(max_length=500)),
                ('vendor_address', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos_base.baseproduct')),
            ],
        ),
    ]
