# Generated by Django 4.1.4 on 2022-12-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='visit_counter',
            field=models.IntegerField(default=0),
        ),
    ]
