# Generated by Django 4.1.4 on 2022-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'administrator'), ('assistant', 'assistant'), ('client', 'client')], default='client', max_length=15),
        ),
    ]
